/**
 * Download US ZCTA centroid coordinates and write a compact JSON lookup table
 * for the marketplace buyer-location UI.
 *
 * Source: 2022 US Census ZCTA gazetteer (via abatko gist mirror of Census data).
 * https://gist.github.com/abatko/00cd3d23b9939e8c9bb20bf9c8e4bfce
 * Official reference: https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE_URL =
  'https://gist.githubusercontent.com/abatko/00cd3d23b9939e8c9bb20bf9c8e4bfce/raw/2022-US-zip-codes-abatko.csv';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_JSON = path.join(__dirname, '../../apps/marketplace/src/data/us-zip-centroids.json');
const OUT_README = path.join(__dirname, '../../apps/marketplace/src/data/README.md');

function roundCoord(value) {
  return Math.round(value * 10_000) / 10_000;
}

function parseCsvLine(line) {
  const [zipRaw, latRaw, lngRaw] = line.split(',').map(part => part.trim());
  if (!zipRaw || !latRaw || !lngRaw) return null;
  const zip = zipRaw.replace(/\D/g, '').padStart(5, '0').slice(0, 5);
  const lat = Number.parseFloat(latRaw);
  const lng = Number.parseFloat(lngRaw);
  if (!/^\d{5}$/.test(zip) || !Number.isFinite(lat) || !Number.isFinite(lng)) return null;
  return { zip, lat: roundCoord(lat), lng: roundCoord(lng) };
}

async function main() {
  const response = await fetch(SOURCE_URL);
  if (!response.ok) {
    throw new Error(`Download failed (${response.status} ${response.statusText})`);
  }

  const text = await response.text();
  const lines = text.split(/\r?\n/);
  const centroids = {};

  for (let i = 1; i < lines.length; i++) {
    const parsed = parseCsvLine(lines[i]);
    if (!parsed) continue;
    centroids[parsed.zip] = { lat: parsed.lat, lng: parsed.lng };
  }

  const count = Object.keys(centroids).length;
  if (count < 30_000) {
    throw new Error(`Unexpectedly low ZIP count (${count}); aborting write`);
  }

  await fs.mkdir(path.dirname(OUT_JSON), { recursive: true });
  await fs.writeFile(OUT_JSON, `${JSON.stringify(centroids)}\n`, 'utf8');

  await fs.writeFile(
    OUT_README,
    `# US ZIP centroid lookup data

Generated by \`npm run geo:download-zips\`.

- **Records:** ${count.toLocaleString()} five-digit ZCTA centroids
- **Source:** 2022 US Census ZCTA gazetteer coordinates (CSV mirror)
- **License:** US government public domain (Census Bureau ZCTA data)

Do not edit \`us-zip-centroids.json\` by hand. Re-run the download script to refresh.
`,
    'utf8',
  );

  const bytes = Buffer.byteLength(JSON.stringify(centroids), 'utf8');
  console.log(`Wrote ${count} ZIP centroids (${(bytes / 1024 / 1024).toFixed(2)} MiB) -> ${OUT_JSON}`);
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
